import 'dart:async';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
// import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:random_string/random_string.dart';
import 'package:tix_movie/cubit/cubit.dart';
import 'package:tix_movie/shared/shared.dart';
import 'package:tix_movie/ui/widget/widget.dart';
import 'package:tix_movie/model/model.dart';
import 'package:tix_movie/services/services.dart';

part 'sign_in_page.dart';
part 'main_page.dart';
part 'succes_page.dart';
part 'splash_screen_page.dart';
part 'detail_movie_page.dart';
part 'order_page.dart';
part 'payment_page.dart';
part 'wallet_page.dart';
part 'ticket_page.dart';
part 'setting_page.dart';
part 'schedule_page.dart';
part 'sign_up_page.dart';
part 'preference_page.dart';
part 'movie_page.dart';
part 'bonus_page.dart';
part 'top_up_page.dart';
part 'ticket_detail.dart';
part 'list_transaction_page.dart';
